legoland/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Product, Order, orderdetails
from datetime import datetime
from .forms import CheckoutForm, SupportForm
from . import db

bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    mostpopular = []
    products = Product.query.order_by(Product.numreviews).all()
    for x in range(4):
        mostpopular.append(products[x])
    return render_template('home.html', products=mostpopular)


@bp.route('/home')
def home():
    mostpopular = []
    products = Product.query.order_by(Product.numreviews).all()
    for x in range(4):
        mostpopular.append(products[x])
    return render_template('home.html', products=mostpopular)


@bp.route('/support', methods=['POST', 'GET'], strict_slashes=False)
def support():
    form = SupportForm()
    if form.validate_on_submit():
        try:
            flash(
                'Thank you for getting in touch! Our team will be in contact soon')
            return redirect(url_for('main.home'))
        except:
            return 'There was an issue submitting the form'
    return render_template('support.html', form=form)


@bp.route('/shop/<string:sortby>')
def shop(sortby):
    # USING SORT BY TO FILTER PRODUCTS ON SHOP PAGE
    if(sortby == 'review'):
        products = Product.query.order_by(Product.fullstar.desc()).all()
    elif(sortby == 'price'):
        products = Product.query.order_by(Product.price).all()
    else:
        products = Product.query.order_by(Product.numreviews.desc()).all()
    return render_template('shop.html', products=products, sortby=sortby)


@bp.route('/shop/')
def search():
    originalSearch = request.args.get('search')
    search = '%{}%'.format(originalSearch)
    products = Product.query.filter(Product.name.like(search)).all()
    return render_template('shop.html', products=products, search=originalSearch)


@bp.route('/product/<int:productid>/')
def product(productid):
    product = Product.query.get(productid)
    return render_template('product.html', product=product)


@bp.route('/order', methods=['POST', 'GET'])
def order():
    product_id = request.values.get('product_id')

    # retrieve order if there is one
    if 'order_id' in session.keys():
        order = Order.query.get(session['order_id'])
        # order will be None if order_id stale
    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order(status=False, firstname='', surname='',
                      email='', phone='', totalcost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('failed at creating a new order')
            order = None

    # calculate totalprice
    totalprice = 0
    if order is not None:
        for product in order.products:
            totalprice = totalprice + product.price

    # are we adding an item?
    if product_id is not None and order is not None:
        product = Product.query.get(product_id)
        if product not in order.products:
            try:
                order.products.append(product)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your basket'
            return redirect(url_for('main.order'))
        else:
            flash('Product already in basket')
            return redirect(url_for('main.order'))
    if (len(order.products) == 0):
        if 'order_id' in session:
            flash('No products on the basket!')
            return redirect(url_for('main.home'))
    # products = Product.query.order_by(Product.name).all()
    return render_template('order.html', order=order, totalprice=totalprice)

# Delete specific basket items


@bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id = request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        product_to_delete = Product.query.get(id)
        try:
            order.products.remove(product_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.home'))

# Scrap basket


@bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.index'))


@bp.route('/checkout', methods=['POST', 'GET'], strict_slashes=False)
def checkout():
    form = CheckoutForm()
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            totalcost = 0
            for product in order.products:
                totalcost = totalcost + product.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash(
                    'Thank you for buying our products!')
                return redirect(url_for('main.home'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form=form)

legoland/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description" content="Legoland">

    <!-- Bootstrap Required Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Legoland</title>

    <!-- Bootstrap CSS -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='../static/img/logo.jpg')}}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='../static/css/app.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
</head>

<body>

    <!-- Contains the heading, navigation and banner image -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-warning">
            <div class="container-fluid">

                <div style="margin-right:15px">
                    <a href="/">
                        <img style="height: 40px" src="{{url_for('static', filename='img/logo.jpg')}}" alt="Logo">
                    </a>
                </div>
                <a href="/" class="navbar-brand">
                    Legoland
                </a>

                <button class="navbar-toggler" style="outline: none!important;" type="button" data-toggle="collapse"
                    data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Navbar -->
                <div class="collapse navbar-collapse justify-content-end" id="navbarToggler">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link text-center" href="/shop/most-popular">Shop</a>
                        <a class="nav-item nav-link text-center" href="/support">Support</a>
                        <a class="nav-item nav-link text-center" href="#">About</a>
                        <div class="ml-md-4 ml-sm-0 nav-item text-center justify-content-end" style="width: 100%;">
                            <form class="form-inline text-center" action="{{ url_for('main.search') }}"
                                style="max-width: 400px; display: inline-block">
                                <input style="border-radius: 10px" class="form-control mr-sm-2" type="search"
                                    placeholder="Search" aria-label="Search" name="search">
                                <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        {% block head %}{% endblock %}
    </header>

    <!-- Contains the main content of the website, divided into sections -->
    <main>
        {% block main %}{% endblock %}
        <section class="subscription-box bg-warning">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="subscribe">
                            <h2 class="text-dark">Want to stay tuned?</h2>
                            <div class="input-group">
                                <input type="email" class="form-control" placeholder="Enter your email" aria-label=""
                                    aria-describedby="basic-addon1">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="button">Subscribe</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <!-- Footer of the website -->
    <footer class="footer">
        <div class="py-2 bg-dark">
            <span class="ml-2 text-light">Copyright &copy; 2020 - Legoland | All Rights Reserved</span>
        </div>
    </footer>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

legoland/templates/checkout.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block head %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-warning" style="color: #343a40; border: none" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}
{% endwith %}
<section class="bread-crumbs">
    <div class="container-fluid">
        <div class="wrapper row">
            <span class="container-fluid text-dark ">
                <a href="/home" class="text-dark">Home</a> > <a href="/shop/most-popular" class="text-dark">Shop</a> >
                <a href="/order" class="text-dark">Order</a> > Checkout
            </span>
        </div>
    </div>
</section>
{% endblock %}

{% block main %}
<section>
    <div class="container-fluid mb-3">
        <div class="card product-detail">
            <div class="container-fluid">
                <div class="wrapper row">
                    <div class="col-12">
                        <h1>You are almost done!</h1>
                        <p>
                            Please provide your details to finalise the purchase and proceed with the payment
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-12">
                        {{wtf.quick_form(form)}}
                    </div>
                    <div class="col-lg-6 d-none d-lg-block">
                        <img class="d-block w-100" src="{{url_for('static', filename='img/lego_checkout.jpeg')}}"
                            alt="Checkout">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

legoland/templates/home.html
{% extends 'base.html' %}

{% block head %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-warning" style="color: #343a40; border: none" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}
{% endwith %}
<section>
    <div class="bg-white mt-3 mb-0" style="min-height: 70px">
        <h1 class="container-fluid text-center text-dark">
            Welcome to Legoland
        </h1>
    </div>
</section>
<section>
    <div class="card card-image" style="cursor: pointer">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators" style="color: black;">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active text-center">
                    <div class="carousel-text d-none d-md-block">
                        <div class="col-md-12 text-center">
                            <h2>
                                <span>May the fourth be with you</span>
                            </h2>
                        </div>
                    </div>
                    <img class="d-block w-100" src="{{url_for('static', filename='img/carousel1.jpg')}}"
                        alt="First slide">
                </div>
                <div class="carousel-item">
                    <div class="carousel-text d-none d-lg-block">
                        <div class="col-md-12 text-center">
                            <h2>
                                <span>New Star Wars figures in stock</span>
                            </h2>
                        </div>
                    </div>
                    <img class="d-block w-100" src="{{url_for('static', filename='img/carousel2.jpg')}}"
                        alt="Second slide">
                </div>
                <div class="carousel-item">
                    <div class="carousel-text d-none d-lg-block">
                        <div class="col-md-12 text-center">
                            <h2>
                                <span>Need help? Talk to our Team</span>
                            </h2>
                        </div>
                    </div>
                    <img class="d-block w-100" src="{{url_for('static', filename='img/carousel3.jpg')}}"
                        alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</section>
{% endblock %}

{% block main %}
<section style="margin: 20px 0 20px 0">
    <h1 class="text-center text-dark">Most Popular</h1>
    <div class="container-fluid">
        <div class="card-deck home-center-items">
            {% for product in products%}
            <div class="col-xl-3 col-lg-4 col-md-4 col-sm-6 col-xs-12 text-dark">
                <a href="{{ url_for('main.product', productid=product.id) }}">
                    <img class="card-img-top" src="{{url_for('static', filename='img/' + product.image)}}"
                        height="250px" alt="Card Image">
                </a>
                <div class="card-body text-center">
                    <a href="{{ url_for('main.product', productid=product.id) }}">
                        <h3 class="card-title text-truncate mb-0">{{product.name}}</h3>
                        <div class="text-warning">
                            {% if product.fullstar > 0 %}
                            {% for review in range(0, product.fullstar)%}
                            <span class="fas fa-star"></span>
                            {% endfor %}
                            {% endif %}
                            {% if product.halfstar %}
                            {% for review in range(0, 1)%}
                            <span class="fa fa-star-half-alt"></span>
                            {% endfor %}
                            {% endif %}
                            {% if product.emptystar > 0 %}
                            {% for review in range(0, product.emptystar)%}
                            <span class="far fa-star"></span>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <p>${{'%0.2f'% product.price}}</p>
                    </a>
                    <form action="{{ url_for('main.order') }}">
                        <input type="hidden" id="product_id" name="product_id" value="{{ product.id }}">
                        <!-- <input class="btn btn-danger btn-md" type="submit" value="Add to Cart"> -->
                        <button type="submit" class="btn btn-danger btn-md"><i class="fas fa-shopping-cart"></i>Add to
                            Cart</button>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

legoland/templates/order.html
{% extends 'base.html' %}

{% block head %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-warning" style="color: #343a40; border: none" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}
{% endwith %}
<section class="bread-crumbs">
    <div class="container-fluid">
        <div class="wrapper row">
            <span class="container-fluid text-dark ">
                <a href="/home" class="text-dark">Home</a> > <a href="/shop/most-popular" class="text-dark">Shop</a> >
                Cart
            </span>
        </div>
    </div>
</section>
{% endblock %}

{% block main %}
<!-- display contents of user basket -->

{% for product in order.products %}
<div class="container-fluid" style="border: none; padding: 10px">
    <div class="card product-detail">
        <div class="container-fluid">
            <div class="wrapper row">
                <div class="col-lg-3">
                    <img style="border: none" class="img-thumbnail"
                        src="{{url_for('static', filename=('img/' + product.image))}}">
                </div>
                <div class="details col-lg-9">
                    <h5>{{product.name}}</h5>
                    <!-- Item Description -->
                    <p class="card-text">{{product.shortdescription}}</p>
                    <h5>{{ "$%.2f"|format(product.price) }}</h5>

                    <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                        <input type="hidden" id="id" name="id" value="{{product.id}}">
                        <button type="submit" class="align-self-end btn btn-secondary mb-3"><i
                                class="far fa-trash-alt mr-1"></i>Remove</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}


<section class="mb-3 text-center">
    <div class="container-fluid">
        <div class="wrapper row">
            <div class="container-fluid text-dark ">
                <a href="/shop/most-popular" class="btn btn-warning mt-4 mr-4"><i class="fas fa-shopping-cart"></i>Shop
                    More</a>
                <a href="{{ url_for('main.deleteorder') }}" class="btn btn-secondary mt-4"><i
                        class="far fa-trash-alt mr-1"></i>Empty Basket</a>
                <h5 class="mt-4">Total Price: <b>${{'%0.2f'% totalprice}}</b></h5>
                <br>
                <a href="{{ url_for('main.checkout') }}" class="btn btn-danger mr-4"><i
                        class="fas fa-arrow-circle-right"></i>Checkout</a>

            </div>
        </div>
    </div>
</section>

{% endblock %}

legoland/templates/product.html
{% extends 'base.html' %}

{% block head %}
<section class="bread-crumbs">
    <div class="container-fluid">
        <div class="wrapper row">
            <span class="container-fluid text-dark ">
                <a href="/home" class="text-dark">Home</a> > <a href="/shop/most-popular" class="text-dark">Shop</a> >
                {{product.shortdescription}}
            </span>
        </div>
    </div>
</section>
{% endblock %}

{% block main %}
<div class="container-fluid">
    <div class="card product-detail">
        <div class="container-fluid">
            <div class="wrapper row">
                <section class="col-lg-7 col-md-12">
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators" style="color: black;">
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active text-center">
                                <img class="d-block w-100" src="{{url_for('static', filename='img/' + product.image)}}"
                                    alt="First slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="{{url_for('static', filename='img/' + product.image)}}"
                                    alt="First slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="{{url_for('static', filename='img/' + product.image)}}"
                                    alt="Third slide">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button"
                            data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button"
                            data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </section>
                <div class="details col-lg-5 col-md-12">
                    <h3>{{product.name}}</h3>
                    <div class="text-warning">
                        {% if product.fullstar > 0 %}
                        {% for review in range(0, product.fullstar)%}
                        <span class="fas fa-star"></span>
                        {% endfor %}
                        {% endif %}
                        {% if product.halfstar %}
                        {% for review in range(0, 1)%}
                        <span class="fa fa-star-half-alt"></span>
                        {% endfor %}
                        {% endif %}
                        {% if product.emptystar > 0 %}
                        {% for review in range(0, product.emptystar)%}
                        <span class="far fa-star"></span>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <span class="reviews">{{product.numreviews}} reviews</span>
                    <p class="product-description">{{product.shortdescription}}</p>
                    <h4 class="product-price">${{'%0.2f'% product.price}}</h4>
                    <div class="action mt-2">
                        <form action="{{ url_for('main.order') }}">
                            <input type="hidden" id="product_id" name="product_id" value="{{ product.id }}">
                            <button type="submit" class="btn btn-danger btn-md col-md-12 mb-3"><i
                                    class="fas fa-shopping-cart"></i>Add to
                                Cart</button>
                        </form>
                        <div class="container-fluid">
                            <div class="row">
                                <button type="button" class="btn btn-md col-md-6"><i
                                        class="fas fa-share-alt"></i>Share</button>
                                <button type="button" class="btn btn-md col-md-6"><i
                                        class="fas fa-heart"></i>Wishlist</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid mt-3 mb-4">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="description-tab" data-toggle="tab" href="#description" role="tab"
                aria-controls="description" aria-selected="true">Description</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="specification-tab" data-toggle="tab" href="#specification" role="tab"
                aria-controls="specification" aria-selected="false">Specification</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="reviews-tab" data-toggle="tab" href="#reviews" role="tab" aria-controls="reviews"
                aria-selected="false">Reviews</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
            {{product.fulldescription}}</div>
        <div class="tab-pane fade" id="specification" role="tabpanel" aria-labelledby="specification-tab">
            {{product.specification}}</div>
        <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
            <div class="container-fluid review-box"></div>
            <div class="review pt-4 pb-4">
                <div class="media">
                    <i class="fas fa-user-circle fa-3x"></i>
                    <div class="media-body">
                        <div class="text-warning">
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star-half-alt"></span>
                        </div>
                        <div>
                            <h6 class="mb-1">John Doe</h6>
                            <p class="review-date">Tue, 7 May 2020</p>
                            <h3 class="review-title col-md-12">Amazing Product</h3>
                            <p class="review-description col-md-12">Bought this for my son and ended up playing with it
                                myself!</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="review pt-4 pb-4">
                <div class="media">
                    <i class="fas fa-user-circle fa-3x"></i>
                    <div class="media-body">
                        <div class="text-warning">
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star-half-alt"></span>
                        </div>
                        <div>
                            <h6 class="mb-1">John Doe</h6>
                            <p class="review-date">Tue, 7 May 2020</p>
                            <h3 class="review-title col-md-12">Amazing Product</h3>
                            <p class="review-description col-md-12">Bought this for my son and ended up playing with it
                                myself!</p>
                        </div>
                    </div>
                </div>
            </div>
            <button class="btn btn-warning text-center w-100 d-block mt-4 font-weight-bold">See All Reviews</button>
        </div>
    </div>
</div>
{% endblock %}

legoland/templates/support.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block head %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-warning" style="color: #343a40; border: none" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}
{% endwith %}
{% endblock %}

{% block main %}
<section>
    <div class="container-fluid mb-3">
        <div class="card product-detail">
            <div class="container-fluid">
                <div class="wrapper row">
                    <div class="col-12">
                        <h1>How can we help?</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-12">
                        {{wtf.quick_form(form)}}
                        <hr class="mt-4 d-md-block d-lg-none">
                        <div style="text-align: center;">
                            <h1 class="d-md-block d-lg-none">Contact Support</h1>
                            <h3 class="d-md-block d-lg-none"><i class="fas fa-phone-volume"></i>001-0800-legoland</h3>
                        </div>
                    </div>
                    <div class="col-lg-1 d-none d-lg-block vl"></div>
                    <div class="col-lg-5 d-none d-lg-block" style="justify-content: center; text-align: center;">
                        <h1>Contact Support</h1>
                        <h3 class="mb-4"><i class="fas fa-phone-volume"></i>001-0800-legoland</h3>
                        <img class="d-block" style="max-height: 283px; margin: auto"
                            src="{{url_for('static', filename='img/contact_us.png')}}" alt="Contact Us">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}